apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prompt-battle
resources:
- namespace.yaml
- secret.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- pvc.yaml
images:
- name: stringju/scg-prompt-battle-prod
  newTag: v5
