apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prompt-battle-data
  labels:
    app.kubernetes.io/name: prompt-battle
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi