apiVersion: v1
kind: Secret
metadata:
  name: prompt-battle-secret
type: Opaque
data:
  PORT: <path:kv/data/prompt-speedrun#PORT | base64encode>
  ADMIN_PASSWORD: <path:kv/data/prompt-speedrun#ADMIN_PASSWORD | base64encode>
  OPENAI_API_KEY: <path:kv/data/prompt-speedrun#OPENAI_API_KEY | base64encode>
  OPENAI_MODEL: <path:kv/data/prompt-speedrun#OPENAI_MODEL | base64encode>